- CollectSFData/App.config
- CollectSFData/CollectSFData.csproj
fix issue #17  Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0
set Microsoft.IdentityModel.Clients.ActiveDirectory to 4.5.1 from 5.0.5 as kusto module has dependency on that version
> fix issue #17  Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.5.1.0

- .github/workflows/labeler.yml
- .github/workflows/workflow.yml
- fix for adal authentication not prompting
- modify EndTimeUtc to always add 30 minutes to compensate for service fabric dtr.zip upload intervals
> fix for adal authentication not prompting

- .github/workflows/workflow.yml
fix workflow for missing exe.config file
> Jagilber  fix workflow for missing exe.config file

- CollectSFData/App.config
- CollectSFData/Azure/BlobManager.cs
- CollectSFData/CollectSFData.csproj
- CollectSFData/Common/ConfigurationOptions.cs
- CollectSFData/Common/Program.cs
- CollectSFData/File/CsvCounterRecord.cs
- CollectSFData/File/CsvExceptionRecord.cs
- CollectSFData/File/CsvSetupRecord.cs
- CollectSFData/File/CsvTableRecord.cs
- CollectSFData/File/DtrTraceRecord.cs
- CollectSFData/File/FileManager.cs
- CollectSFData/File/FileObject.cs
- CollectSFData/File/IRecord.cs
- CollectSFData/File/ITraceRecord.cs
- CollectSFData/Kusto/KustoConnection.cs
- CollectSFData/Kusto/KustoIngestionMappings.cs
- CollectSFData/Properties/AssemblyInfo.cs
2.6 modify gathertype exception to add exception table with blob fileuri records
fix autobind warning kusto.core
> 2.6 modify gathertype exception to add exception table with blob fileuri records

- .github/workflows/workflow.yml
- docs/KustoQueries/kusto-example-queries.csl
- docs/KustoQueries/sfcounters-general.csl
- docs/KustoQueries/sflogs-create-TraceKnownIssue.csl
- docs/LogAnalyticsQueries/log-analytics-example-queries.csl
- docs/logAnalyticsExampleQueries.md
- scripts/kusto-rest.ps1
update release name in workflow
update kusto scripts
> fix workflow release name

- CollectSFData/Common/Program.cs
- CollectSFData/File/DtrTraceRecord.cs
- CollectSFData/File/FileObject.cs
fix for download / upload cache
fix for BaseUri prepend error
> fix for download / upload cache

- .github/workflows/workflow.yml
- CollectSFData/Azure/BlobManager.cs
- CollectSFData/Azure/TableManager.cs
- CollectSFData/Common/ConfigurationOptions.cs
- CollectSFData/Common/Constants.cs
- CollectSFData/Common/Instance.cs
- CollectSFData/Common/Program.cs
- CollectSFData/File/CsvExceptionRecord.cs
- CollectSFData/File/FileManager.cs
- CollectSFData/File/FileObject.cs
- CollectSFData/File/ITraceRecord.cs
- CollectSFData/Kusto/KustoConnection.cs
- CollectSFData/LogAnalytics/LogAnalyticsConnection.cs
- scripts/kusto-rest.ps1
modify gathertype exception functionality to create table without sas and to write to console download link with sas
fix table Timestamp not being converted to UTC
fix download cache for exporting data local scenario
modify release tag to use standard vx.x.x. notation
modify saveconfig to remove gathertype from kusto and LA table names
code formatting
> modify gathertype exception functionality to create table without sas and to write to console download link with sas

- CollectSFData/Azure/BlobManager.cs
- CollectSFData/Common/CommandLineArguments.cs
- CollectSFData/Common/Instance.cs
- CollectSFData/Common/Program.cs
- CollectSFData/File/CsvExceptionRecord.cs
- docs/KustoQueries/sflogs-create-TraceFMMNodeCountsGraph.csl
- docs/KustoQueries/sflogs-create-TraceKnownIssue.csl
- scripts/kusto-rest.ps1
- add additional summary logging with discovered storage account date ranges
- fix for linux .dmp filenames for download
- update kusto query .csl
- update kusto-rest.ps1 for msal
> Jagilber add additional summary logging with discovered storage account date ranges

- .github/workflows/workflow.yml
fix default config file collectsfdata.options.json copy
> fix default config file collectsfdata.options.json copy

- CollectSFData/Common/ConfigurationOptions.cs
- KustoFunctions/sflogs/TraceTypeDistinct.csl
- KustoFunctions/sflogs/TraceTypeNameAndIdView.csl
- KustoFunctions/sflogs/base/CreateKustoWebQueryLink.csl
- KustoFunctions/sflogs/errors/TraceFabric_E_ErrorsDistinct.csl
- KustoFunctions/sflogs/errors/TraceTextErrorCodesDistinct.csl
- KustoFunctions/sflogs/errors/TraceTextExceptionsDistinct.csl
- KustoFunctions/sflogs/errors/TraceTypeErrorsDistinct.csl
- KustoFunctions/sflogs/patch-orchestration/TracePOADistinct.csl
- KustoQueries/example-regex.csl
- configurationFiles/azure.kusto.64.json
- configurationFiles/azure.kusto.65.json
- configurationFiles/collectsfdata.options.json
- configurationFiles/collectsfdata.schema.json
- configurationFiles/standalone.kusto.json
add / modify kusto functions
enable kustocompressed by default
> add / modify kusto functions, enable kustocompressed by default

- CollectSFData/Azure/BlobManager.cs
- CollectSFData/CollectSFData.csproj
- CollectSFData/Common/CommandLineArguments.cs
- CollectSFData/Common/ConfigurationOptions.cs
- CollectSFData/Common/CustomTaskManager.cs
- CollectSFData/Common/Http.cs
- CollectSFData/Common/Instance.cs
- CollectSFData/Common/Program.cs
- CollectSFData/File/FileManager.cs
- CollectSFData/File/FileObject.cs
- CollectSFData/File/FileTypes.cs
- CollectSFData/Kusto/KustoConnection.cs
- CollectSFData/Kusto/KustoEndpointInfo.cs
- CollectSFData/Kusto/KustoRestResponseV1.cs
- CollectSFData/Kusto/KustoRestTable.cs
- CollectSFData/Kusto/KustoRestTableOfContentsV1.cs
- CollectSFData/LogAnalytics/LogAnalyticsConnection.cs
- KustoFunctions/sflogs/errors/TraceTypeErrorsDistinct.csl
- configurationFiles/collectsfdata.options.json
- configurationFiles/collectsfdata.schema.json
- docs/configuration.md
add support for large blob sizes
fix file handling for 'any' gather type
save data files
add servicepointmanager options
draft KustoUseIngestMessage for better ingest performance
add KustoIngestMessage documentation
add support for null and 0 thread value
> draft KustoUseIngestMessage

- CollectSFData/Kusto/KustoConnection.cs
- CollectSFData/Kusto/KustoEndpointInfo.cs
fix for distinct RelativeUri query for ingestion_time(). add logging
fix for UniversalTime conversion
> fix for distinct RelativeUri query for ingestion_time(). add logging

- CollectSFData/Azure/BlobManager.cs
- CollectSFData/Common/ConfigurationOptions.cs
- KustoFunctions/sflogs/base/TraceKnownIssue.csl
fixes for gathertype any downloads
disable kusto for gathertype any
disable downloads if file exists in download cache
add total skipped counter if file exists in download
update known issues kusto function
> fixes for gathertype any downloads

- CollectSFData/Azure/SasEndpoints.cs
- CollectSFData/Common/CommandLineArguments.cs
- CollectSFData/Common/ConfigurationOptions.cs
- CollectSFData/Common/Instance.cs
- CollectSFData/Common/Program.cs
- CollectSFDataTests/TestConfigurations/collectsfdata.options.json
- CollectSFDataTests/TestFiles/SasUriTests.json
- CollectSFDataTests/TestUtilities/TestProperties.cs
- CollectSFDataTests/TestUtilities/TestUtilities.cs
- CollectSFDataTests/Tests/FileUriTests.cs
- CollectSFDataTests/Tests/GatherTypeTests.cs
- CollectSFDataTests/Tests/SasUriTests.cs
- README.md
- configurationFiles/collectsfdata.options.json
- configurationFiles/collectsfdata.schema.json
- docs/configuration.md
add NoProgressTimeoutMin property
add NoProgressTimeoutMin documentation
add Tests
> add NoProgressTimeoutMin property

- CollectSFDataTests/CollectSFDataTests.csproj
- CollectSFDataTests/TestUtilities/TestUtilities.cs
- CollectSFDataTests/TestUtilities/setup-test-env.ps1
- CollectSFDataTests/Tests/FileUriTests.cs
- CollectSFDataTests/Tests/GatherTypeTests.cs
- CollectSFDataTests/Tests/SasUriTests.cs
- CollectSFDataTests/packages.config
> switch from MSTest to NUnit

- CollectSFData/Kusto/KustoConnection.cs
- CollectSFData/Kusto/KustoEndpointInfo.cs
Ingesting mapping of ResourceURI to table name. This will aid in correlating traces to run insights and detectors easily
> Ingesting mapping of ResourceURI to table name

- CollectSFData/Kusto/KustoConnection.cs
CollectSFData/Kusto/KustoConnection.cs add check _ingestedUris.Any() before querying for resourceUri to prevent errors in logging
> CollectSFData/Kusto/KustoConnection.cs add check _ingestedUris.Any()

- CollectSFData/CollectSFData.nuspec
> changes for oss

- CollectSFData/CollectSFData.nuspec
add $version$
add default collectsfdata.options.json
fix missing collectsfdata.exe.config
fix nuget package contents target path
> CollectSFData/CollectSFData.nuspec add $version$ and default config json, fix missing .config

- .github/workflows/workflow.yml
CollectSFData/CollectSFData.nuspec clean release notes
> Release CollectSFData/CollectSFData.nuspec clean release notes

- CollectSFData/DataFile/FileManager.cs
- CollectSFData/DataFile/StreamManager.cs
- CollectSFData/Kusto/KustoEndpointInfo.cs
clean CollectSFData/Kusto/KustoEndpointInfo.cs unused code / comments
make stream and file functions more intuitive
CollectSFData/DataFile/FileManager.cs
CollectSFData/DataFile/StreamManager.cs
> code cleanup

- CollectSFDataTests/CollectSFDataTests.csproj
fix for git dependency flagging System.Management.Automation package in test project as security vulnerability
> fix for git dependency flagging package in test project

- CollectSFData.sln
.net 472
.netcoreapp3.1
msal
collectsfdata.exe
collectsfdata.dll
thread fix
> dll build pre-release

- CollectSFDataDll/Azure/AzureResourceManager.cs
- CollectSFDataDll/Azure/TableManager.cs
- CollectSFDataDll/Common/ConfigurationOptions.cs
- CollectSFDataDll/Common/Http.cs
- CollectSFDataDll/Common/Log.cs
- scripts/install-kusto-functions.ps1
dll and exe
.net472 and .netcoreapp3.1
msal client, user, device logon
add object, counter, instance fields for gathertype counter
fixed temp dir saveconfig in json output
task scheduler thread race fix
logdebug now int with levels 0 - 5
> 2.7 Dll / exe

- CollectSFData/CollectSFData.nuspec
- scripts/dotnet-build.ps1
separate lib into lib and tools
/lib allows nuget package manager to add as package and  as assembly reference
/tools has exe with all dependencies
> collectsfdata.nuspec fix layout separate into tools and lib for npm

- .devcontainer/Dockerfile
codespace add new process for net5 download / install
> codespace add new process for net5 download / install

- kusto/functions/sflogs/TraceKnownIssueSummary.csl
- kusto/functions/sflogs/base/TraceKnownIssue.csl
kusto/functions/sflogs/base/TraceKnownIssue.csl KustoFunction add link field
> kusto/functions/sflogs/base/TraceKnownIssue.csl KustoFunction add link field

- .github/labeler.yml
- scripts/dotnet-build.ps1
- src/CollectSFDataDll/Collector.cs
- src/CollectSFDataDll/Common/CustomTaskManager.cs
- src/CollectSFDataDll/Kusto/KustoConnection.cs
- src/CollectSFDataDll/Kusto/KustoQueueMessage.cs
fix remove taskmanager.cancel() for retry causing hang
fix ingest message compare not always removing messages from pending queue causing timeout
> 12/31 fix remove taskmanager.cancel() for retry

- src/CollectSFData/CollectSFData.nuspec
add Tx*.dll to nuspec file copy
> add Tx*.dll to nuspec file copy

- CHANGELOG.md
add Tx*.dll to nuspec file copy
> 2.8 nuget fix

- .github/labeler.yml
- CHANGELOG.md
- kusto/functions/sflogs/TraceGuestProcesses.csl
- src/CollectSFData/CollectSFData.csproj
- src/CollectSFData/CollectSFData.nuspec
- src/CollectSFData/Program.cs
- src/CollectSFDataDll/CollectSFDataDll.csproj
- src/CollectSFDataDll/Collector.cs
- src/CollectSFDataDll/Common/ConfigurationOptions.cs
- src/CollectSFDataDll/Common/Log.cs
- src/CollectSFDataDll/DataFile/FileManager.cs
- src/Tx/Tx.Core/Tx.Core.csproj
- add System.Reactive dependency for Tx
- add uris argument to UpdloadData()
- modify PopulateConfig() to use GatherType to determine if configuration populated
- fix CheckLogFile to not check file if open
- fix table name prepend to prevent duplicate
- fix file name with multiple splits from concatenating counters in name
> 2.8 Build Pre-release stage

- CHANGELOG.md
- docs/dllConfiguration.md
- kusto/functions/sflogs/base/TracesNearTimestamp.csl
- src/CollectSFDataDll/DataFile/FileManager.cs
- fix offset fields in gathertype 'setup'
-
> fix offset fields in gathertype 'setup'

- CHANGELOG.md
- src/CollectSFData/CollectSFData.csproj
- src/CollectSFData/CollectSFData.nuspec
- src/CollectSFDataDll/CollectSFDataDll.csproj
- src/CollectSFDataDll/Kusto/KustoConnection.cs
net462 kusto / newtonsoft downgrade for jarvis asc integration
> net462 kusto / newtonsoft downgrade

- src/CollectSFData/CollectSFData.nuspec
new parameters AzureClientCertificate and AzureKeyVault have been added for non interactive confidential client logons
see configuration documents for examples
fix for nuget package layout for net5.0
> add client certificate authorization for confidential client

- src/CollectSFDataDll/Common/ConfigurationOptions.cs
- src/CollectSFDataDll/Common/Http.cs
fix for downloading manifests (non json result)
> fix for downloading manifests (non json result)

- CHANGELOG.md
- src/CollectSFDataDll/Azure/BlobManager.cs
- src/SECURITY.md
fix for Geneva storage needing CloudStorageAccount.UseV1MD5 = false
> fix for Geneva storage needing CloudStorageAccount.UseV1MD5 = false

- CHANGELOG.md
- scripts/nuget-functions.ps1
- src/CollectSFData/CollectSFData.csproj
- src/CollectSFData/CollectSFData.nuspec
- src/CollectSFDataDll/CollectSFDataDll.csproj
add explicit reference to microsoft.identity.client 4.42.0 for jarvis error
> add explicit reference to microsoft.identity.client 4.42.0 for jarvis error

- src/CollectSFData/CollectSFData.csproj
- src/CollectSFData/CollectSFData.nuspec
- src/CollectSFDataDll/Azure/AzureResourceManager.cs
- src/CollectSFDataDll/CollectSFDataDll.csproj
- src/CollectSFDataDll/Kusto/KustoEndpoint.cs
fix "AADSTS1002012: The provided value for scope https://.../user_impersonation is not valid. Client credential flows
> fix "AADSTS1002012: The provided value for scope https://.../user_impersonation is not valid. Client credential flows

- scripts/collectsfdata-ps.ps1
- src/CollectSFDataDll/Azure/BlobManager.cs
- src/CollectSFDataDll/Azure/ClientIdentity.cs
- src/CollectSFDataDll/Azure/TableManager.cs
- src/CollectSFDataDll/Common/ConfigurationOptions.cs
- src/CollectSFDataDll/Common/Constants.cs
- src/CollectSFDataDll/Common/Http.cs
add public ip address check/logging for storage authentication errors '1:CheckPublicIp:for storage authentication errors, add public ip address to nsg / storage firewall: xxx.xxx.xxx.xxx'
fix CheckInstanceMetaDataEndpoint() false positive 
fix CheckInstanceMetaDataEndpoint() hang waiting on tcp timeout
> add public ip address check/logging for storage authentication errors 

- .vscode/settings.json
- docs/contributing.md
- scripts/collectsfdata-ps.ps1
- scripts/post-build-events.ps1
- src/CollectSFData/CollectSFData.csproj
- src/CollectSFData/CollectSFData.nuspec
- src/CollectSFDataDll/CollectSFDataDll.csproj
Add net8.0 back as a target framework
Remove net6.0 and net4.8 from nupkg tools/ (still in lib/) to reduce size
> Dev 30 add net8.0 back as a target framework. remove net6.0 and net4.8 from nupkg tools/ (still in lib/) to reduce size
